#!/bin/bash

### BEGIN INIT INFO
# Provides:          crucible                                               
# Required-Start:    $local_fs $syslog 
# Required-Stop:     $local_fs $syslog                                      
# Default-Start:     2 3 4 5                                                          
# Default-Stop:      0 1 6                                                            
# Short-Description: Crucible                                             
# Description:       Atlassian Crucible
### END INIT INFO                

# set JAVA_HOME and FISHEYE_INST in /etc/environment 
#JAVA_HOME="/usr/local/src/jdk1.7.0_13/"
#FISHEYE_INST="/var/crucible_data/"

CRUCIBLE_USER=crucible
CRUCIBLE_HOME=/usr/local/src/fecru-2.9.2/bin/

start() {
        echo "Starting Crucible: "
        if [ "x$USER" != "x$CRUCIBLE_USER" ]; then
          su - $CRUCIBLE_USER -c "$CRUCIBLE_HOME/fisheyectl.sh start"
        else
          $CRUCIBLE_HOME/fisheyectl.sh start
        fi
        echo "done."
}
stop() {
        echo "Shutting down Crucible: "
        if [ "x$USER" != "x$CRUCIBLE_USER" ]; then
          su - $CRUCIBLE_USER -c "$CRUCIBLE_HOME/fisheyectl.sh stop"
        else
          $CRUCIBLE_HOME/fisheyectl.sh stop
        fi
        echo "done."
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        sleep 10
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
esac

exit 0
